
## SET VERIFY OFF - NO DISPLAY AND NO RUNNING
SET VERIFY OFF;
DEFINE MY_SALARY = 140000;

SELECT * FROM employees WHERE salary >= &MY_SALARY;

UNDEFINE MY_SALARY



## SET VERIFY ON- DISPLAY AND RUNNING
SET VERIFY ON;
DEFINE MY_SALARY = 140000;

SELECT * FROM employees WHERE salary >= &MY_SALARY;

UNDEFINE MY_SALARY